[project]
name = "connect4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.0",
    "numpy==2.2.3",
    "torch==2.6.0",
    "pytest==8.3.4",
    "ruff>=0.11.2",
]
